version: "3"
services:
  api:
    restart: always
    build: .
    ports:
      - "127.0.0.1:4000:3000"
    depends_on:
      - "db"
    volumes: 
      - ./.place-data:/user/src/app/.place-data
    environment:
      NODE_ENV: "production"
      DATABASE: "mongodb://db/place"
      PORT: 3000
      ONLY_LISTEN_LOCAL: "false"
  db:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
